Adding trigger to calculate solme fields
3liz/qgis-pgmetadata-plugin pull request #12
Opened 2020-10-27 16:48 UTC by drillinP

* Ticket : #10 
*

2020-10-28 08:17 UTC, Gustry commented on pg_metadata/test/test_database_structure.py
> +        self.assertEqual('0.0.4', results['DATABASE_VERSION'])
Thanks for reminding this one. It has been fixed on master. You can rollback this change and rebase on master.

2020-10-28 12:03 UTC, Gustry reviewed
* Can you add a test ? There is a line layer in the database. Look in `test_sql.py` for an example.
* Does that work with a geometry less table ?

Can you rebase again on master ? I have included some tests on CI. Sorry for this.

2020-10-28 12:41 UTC, Gustry commented
FYI, I have just added a geometry less table in the test database, if you rebase on master.

2020-10-28 14:16 UTC, drillinP commented on pg_metadata/install/sql/pgmetadata/10_FUNCTION.sql
> +	ma_table = CONCAT(NEW.schema_name, '.', NEW.table_name);
`table` it's a sql term. So this time we need prefix.

2020-10-28 14:31 UTC, Gustry commented on pg_metadata/install/sql/pgmetadata/10_FUNCTION.sql
> +	ma_table = CONCAT(NEW.schema_name, '.', NEW.table_name);
Ok !

2020-10-28 16:20 UTC, mdouchin requested changes

2020-10-28 16:20 UTC, mdouchin commented on pg_metadata/install/sql/pgmetadata/10_FUNCTION.sql
> +    WHERE table_schema=''' || NEW.schema_name || ''' AND table_name=''' || NEW.table_name || ''' and column_name=''geom'' ' INTO test_geom;
To test if the table has a geometry column, I would use a direct SQL query on the `public.geometry_columns` table such as

```sql
SELECT * 
FROM geometry_columns WHERE f_table_schema = 'NOM_SCHEMA' AND f_table_name = 'NOM_TABLE' 
INTO geometry_columns_rec;
```
(this is an example, replace with the NEW.schema_name and table_name)
which will return nothing if no line is found, but a record with geometry_columns data if sucess.

If you modify the  `DECLARE` to add a new param: `geometry_columns_rec record;` which will receive the result of this query

This way you will be able to use directly the `geometry_columns_rec.geometry_type` like

```sql
NEW.geometry_type = geometry_columns_rec.geometry_type;
```

2020-10-28 16:20 UTC, mdouchin commented on pg_metadata/install/sql/pgmetadata/20_TABLE_SEQUENCE_DEFAULT.sql
> +    geom public.geometry
I think we should keep use a geometry(Polygon,4326) here and use the `ST_Transform()` method to create the geometry from the table convex hull

2020-10-28 16:20 UTC, mdouchin commented on pg_metadata/install/sql/upgrade/upgrade_to_0.0.4.sql
> +ALTER TABLE pgmetadata.dataset ALTER COLUMN geom TYPE geometry;
Please keep geometry(Polygon, 4326) as explained above

2020-10-29 13:42 UTC, Gustry reviewed
I just reviewed the code about the Python side.

2020-10-29 13:42 UTC, Gustry commented on pg_metadata/test/test_sql.py
> +        # Now with new table whithout geom column
```suggestion
    def test_trigger_calculate_fields_without_geom(self):
        """ Test the trigger on a geometry less table. """
```

@drillinP Il est conseillé de découper un test dés que le code qui suit n'a pas de lien avec le code précédent.
Comme ca, quand un test plante, cela ne stop pas les autres parties du code au sein du test (qui peut peut-être être OK)

2020-10-29 13:42 UTC, Gustry commented on pg_metadata/test/test_sql.py
> +        # First with removing geom column
```suggestion
        # Test with removing the geom column
```

@drillinP The is a difference between `""" Docstring """` and `# Comment`.

`""" Docstring... """` which must be unique (in a function) and at the top of the function. It's designed for documentation of the code and for display outside (when running tests for instance).

` # My comment` is designed for developpers, to give some comments about a specific block of code. It won't be displayed outside of the file or outside the code editor.

2020-10-29 13:42 UTC, Gustry commented on pg_metadata/test/test_sql.py
> +        """ Test with geom column """
```suggestion
    def test_trigger_calculate_fields_with_geom(self):
        """ Test if fields are correctly calculated on a layer having a geometry. """
```

2020-10-29 14:44 UTC, Gustry commented on pg_metadata/test/test_sql.py
> +        # Test with new table whithout geom column
@drillinP C'est ici que je demandais de couper le code. Le code en-dessous est un nouveau test, car le code en-dessous ne dépend pas du code au dessus. En le découpant, on s'assure que le test est bien "unitaire" comme son nom l'indique.

```suggestion
        def test_trigger_calculate_fields_without_geom(self):
            """ Test compute fields on a geometry less table. """
```

2020-10-29 14:44 UTC, Gustry commented on pg_metadata/test/test_sql.py
> +        """ Test the trigger on a geometry less table. """
Je pensais à cette coupure, mais je l'avais pas demandé, car c'était l'autre coupure. ;-)
Gardons la maintenant que c'est fait, mais par contre il faut renommer avec mon autre suggestion.

```suggestion
    def test_trigger_calculate_fields_when_removing_geom(self):
        """ Test the trigger on an existing table where we remove the geometry. """
```

2020-10-29 15:20 UTC, Gustry reviewed
LGTM for 🐍 (Python snake), I will let @mdouchin review the SQL 🐘
I read the SQL, it looks OK to me, but I haven't tried it.

2020-10-30 14:04 UTC, mdouchin commented
@drillinP @Gustry I have 

* rewritten the SQL trigger function to always calculate the fields with RAISE NOTICE & better code readability
* added a function `pgmetadata.refresh_dataset_calculated_fields()` to manually refresh all dataset features
* I need to modify the upgrade SQL file !

2020-10-30 14:19 UTC, mdouchin commented
Seems ok for me now :)

2020-11-02 08:33 UTC, mdouchin commented
Manually rebasing -> close

2020-11-02 08:33 UTC, closed without merging